# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'static/')),
                ('availabilty', models.BooleanField(default=True)),
            ],
        ),
    ]
